### ISSUE TITLE
Fails silently if buildkite-agent isn't available

### ISSUE THREAD

**Issue by reidab** [sj26/rspec-buildkite#1]
Running with docker-compose, I'd forgotten to mount the buildkite-agent binary into the container. The `system` call returns `false` for the non-zero exit status, but it doesn't raise an exception so no message is displayed in the logs.

**Comment by TigerWolf** [comment]
I would also like to know if it is failing too. Hopefully this will help me work out what is going on.

**Comment by gondalez** [comment]
Thanks for the handy gem!

+1 for expecting a hard failure and/or error message if the agent is not present 🤔 

For others: specifying the env vars and agent mount as part of the docker-compose plugin config worked nicely for me.

`pipeline.yml`
```yml
steps:
  - label: ':rspec:'
    ...snip...
    plugins:
      - docker-compose#v3.0.3:
          ...snip...
          volumes:
            - ${BUILDKITE_AGENT_BINARY_PATH:-/usr/bin/buildkite-agent}:/usr/bin/buildkite-agent
          environment:
            - BUILDKITE
            - BUILDKITE_BUILD_ID
            - BUILDKITE_JOB_ID
            - BUILDKITE_AGENT_ACCESS_TOKEN
```

It's a bit repetitive as mentioned in https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/issues/158, but hopefully that can be resolved within the buildkite plugin 🤞
